import React, { createContext, useContext, useState, useEffect } from 'react';

export const languages = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    diseaseDetection: 'Disease Detection',
    soilAnalysis: 'Soil Analysis',
    medicineGuide: 'Medicine Guide',
    prevention: 'Prevention Tips',
    marketAccess: 'Market Access',
    nutrientDeficiency: 'Nutrient Deficiency',
    pestAlerts: 'Pest Alerts',
    settings: 'Settings',
    helpSupport: 'Help & Support',
    logout: 'Logout',
    welcome: 'Welcome to KissanMitra',
    smartFarming: 'Smart Farming',
    login: 'Login',
    signup: 'Sign Up',
    farmer: 'Farmer',
    wholesaler: 'Wholesaler',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    phone: 'Phone Number',
    location: 'Location',
    continueAs: 'Continue as',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    language: 'Language',
    selectLanguage: 'Select Language',
    chatWithAI: 'Chat with AI',
    askAnything: 'Ask anything about farming...',
    send: 'Send',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    diseaseDetection: 'रोग पहचान',
    soilAnalysis: 'मिट्टी विश्लेषण',
    medicineGuide: 'दवा मार्गदर्शिका',
    prevention: 'रोकथाम सुझाव',
    marketAccess: 'बाजार पहुंच',
    nutrientDeficiency: 'पोषक तत्व की कमी',
    pestAlerts: 'कीट चेतावनी',
    settings: 'सेटिंग्स',
    helpSupport: 'सहायता और समर्थन',
    logout: 'लॉग आउट',
    welcome: 'किसानमित्र में आपका स्वागत है',
    smartFarming: 'स्मार्ट खेती',
    login: 'लॉग इन',
    signup: 'साइन अप',
    farmer: 'किसान',
    wholesaler: 'थोक व्यापारी',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    phone: 'फोन नंबर',
    location: 'स्थान',
    continueAs: 'के रूप में जारी रखें',
    createAccount: 'खाता बनाएं',
    alreadyHaveAccount: 'पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    language: 'भाषा',
    selectLanguage: 'भाषा चुनें',
    chatWithAI: 'AI से बात करें',
    askAnything: 'खेती के बारे में कुछ भी पूछें...',
    send: 'भेजें',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    diseaseDetection: 'ਬਿਮਾਰੀ ਖੋਜ',
    soilAnalysis: 'ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    medicineGuide: 'ਦਵਾਈ ਗਾਈਡ',
    prevention: 'ਰੋਕਥਾਮ ਸੁਝਾਅ',
    marketAccess: 'ਬਾਜ਼ਾਰ ਪਹੁੰਚ',
    nutrientDeficiency: 'ਪੌਸ਼ਟਿਕ ਤੱਤਾਂ ਦੀ ਘਾਟ',
    pestAlerts: 'ਕੀੜੇ ਚੇਤਾਵਨੀ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    helpSupport: 'ਮਦਦ ਅਤੇ ਸਹਾਇਤਾ',
    logout: 'ਲੌਗ ਆਊਟ',
    welcome: 'ਕਿਸਾਨਮਿੱਤਰ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
    smartFarming: 'ਸਮਾਰਟ ਖੇਤੀ',
    login: 'ਲੌਗ ਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    farmer: 'ਕਿਸਾਨ',
    wholesaler: 'ਥੋਕ ਵਪਾਰੀ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    phone: 'ਫੋਨ ਨੰਬਰ',
    location: 'ਸਥਾਨ',
    continueAs: 'ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    alreadyHaveAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    language: 'ਭਾਸ਼ਾ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    chatWithAI: 'AI ਨਾਲ ਗੱਲ ਕਰੋ',
    askAnything: 'ਖੇਤੀ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ...',
    send: 'ਭੇਜੋ',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    diseaseDetection: 'நோய் கண்டறிதல்',
    soilAnalysis: 'மண் பகுப்பாய்வு',
    medicineGuide: 'மருந்து வழிகாட்டி',
    prevention: 'தடுப்பு குறிப்புகள்',
    marketAccess: 'சந்தை அணுகல்',
    nutrientDeficiency: 'ஊட்டச்சத்து குறைபாடு',
    pestAlerts: 'பூச்சி எச்சரிக்கைகள்',
    settings: 'அமைப்புகள்',
    helpSupport: 'உதவி & ஆதரவு',
    logout: 'வெளியேறு',
    welcome: 'கிசான்மித்ராவில் வரவேற்கிறோம்',
    smartFarming: 'ஸ்மார்ட் விவசாயம்',
    login: 'உள்நுழை',
    signup: 'பதிவு செய்',
    farmer: 'விவசாயி',
    wholesaler: 'மொத்த வியாபாரி',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    fullName: 'முழு பெயர்',
    phone: 'தொலைபேசி எண்',
    location: 'இருப்பிடம்',
    continueAs: 'ஆக தொடர்க',
    createAccount: 'கணக்கை உருவாக்கு',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    language: 'மொழி',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    chatWithAI: 'AI உடன் அரட்டை',
    askAnything: 'விவசாயத்தைப் பற்றி எதையும் கேளுங்கள்...',
    send: 'அனுப்பு',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    diseaseDetection: 'వ్యాధి గుర్తింపు',
    soilAnalysis: 'నేల విశ్లేషణ',
    medicineGuide: 'మందుల గైడ్',
    prevention: 'నివారణ చిట్కాలు',
    marketAccess: 'మార్కెట్ యాక్సెస్',
    nutrientDeficiency: 'పోషకాల లోపం',
    pestAlerts: 'పురుగుల హెచ్చరికలు',
    settings: 'సెట్టింగులు',
    helpSupport: 'సహాయం & మద్దతు',
    logout: 'లాగ్ అవుట్',
    welcome: 'కిసాన్‌మిత్రాకు స్వాగతం',
    smartFarming: 'స్మార్ట్ ఫార్మింగ్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    farmer: 'రైతు',
    wholesaler: 'హోల్‌సేలర్',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    phone: 'ఫోన్ నంబర్',
    location: 'స్థానం',
    continueAs: 'గా కొనసాగించు',
    createAccount: 'ఖాతా సృష్టించు',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    dontHaveAccount: 'ఖాతా లేదా?',
    language: 'భాష',
    selectLanguage: 'భాషను ఎంచుకోండి',
    chatWithAI: 'AI తో చాట్',
    askAnything: 'వ్యవసాయం గురించి ఏదైనా అడగండి...',
    send: 'పంపు',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    diseaseDetection: 'রোগ সনাক্তকরণ',
    soilAnalysis: 'মাটি বিশ্লেষণ',
    medicineGuide: 'ওষুধ গাইড',
    prevention: 'প্রতিরোধ টিপস',
    marketAccess: 'বাজার প্রবেশ',
    nutrientDeficiency: 'পুষ্টির অভাব',
    pestAlerts: 'কীট সতর্কতা',
    settings: 'সেটিংস',
    helpSupport: 'সাহায্য ও সমর্থন',
    logout: 'লগ আউট',
    welcome: 'কিষাণমিত্রায় স্বাগতম',
    smartFarming: 'স্মার্ট ফার্মিং',
    login: 'লগ ইন',
    signup: 'সাইন আপ',
    farmer: 'কৃষক',
    wholesaler: 'পাইকারী ব্যবসায়ী',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    fullName: 'পুরো নাম',
    phone: 'ফোন নম্বর',
    location: 'অবস্থান',
    continueAs: 'হিসেবে চালিয়ে যান',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    language: 'ভাষা',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    chatWithAI: 'AI এর সাথে চ্যাট',
    askAnything: 'কৃষি সম্পর্কে কিছু জিজ্ঞাসা করুন...',
    send: 'পাঠান',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    login: 'लॉग इन',
    signup: 'साइन अप',
    farmer: 'शेतकरी',
    wholesaler: 'घाऊक व्यापारी',
    email: 'ईमेल',
    password: 'पासवर्ड',
    fullName: 'पूर्ण नाव',
    settings: 'सेटिंग्ज',
    helpSupport: 'मदत आणि समर्थन',
    language: 'भाषा',
    send: 'पाठवा',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    login: 'લૉગ ઇન',
    signup: 'સાઇન અપ',
    farmer: 'ખેડૂત',
    wholesaler: 'જથ્થાબંધ વેપારી',
    email: 'ઈમેલ',
    password: 'પાસવર્ડ',
    fullName: 'પૂર્ણ નામ',
    settings: 'સેટિંગ્સ',
    helpSupport: 'મદદ અને સપોર્ટ',
    language: 'ભાષા',
    send: 'મોકલો',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    farmer: 'ರೈತ',
    wholesaler: 'ಸಗಟು ವ್ಯಾಪಾರಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    helpSupport: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    language: 'ಭಾಷೆ',
    send: 'ಕಳುಹಿಸಿ',
  },
  ml: {
    dashboard: 'ഡാഷ്ബോർഡ്',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    farmer: 'കർഷകൻ',
    wholesaler: 'മൊത്ത വ്യാപാരി',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    fullName: 'മുഴുവൻ പേര്',
    settings: 'ക്രമീകരണങ്ങൾ',
    helpSupport: 'സഹായവും പിന്തുണയും',
    language: 'ഭാഷ',
    send: 'അയയ്ക്കുക',
  },
  or: {
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    login: 'ଲଗଇନ',
    signup: 'ସାଇନ ଅପ',
    farmer: 'ଚାଷୀ',
    wholesaler: 'ପାଇକାରୀ ବ୍ୟବସାୟୀ',
    email: 'ଇମେଲ',
    password: 'ପାସୱାର୍ଡ',
    fullName: 'ପୂର୍ଣ୍ଣ ନାମ',
    settings: 'ସେଟିଂସ',
    helpSupport: 'ସାହାଯ୍ୟ ଏବଂ ସମର୍ଥନ',
    language: 'ଭାଷା',
    send: 'ପଠାନ୍ତୁ',
  },
  as: {
    dashboard: 'ডেচব\'ৰ্ড',
    login: 'লগ ইন',
    signup: 'চাইন আপ',
    farmer: 'কৃষক',
    wholesaler: 'পাইকাৰী ব্যৱসায়ী',
    email: 'ইমেইল',
    password: 'পাছৱৰ্ড',
    fullName: 'সম্পূৰ্ণ নাম',
    settings: 'ছেটিংছ',
    helpSupport: 'সহায় আৰু সমৰ্থন',
    language: 'ভাষা',
    send: 'পঠাওক',
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('preferredLanguage');
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
